version: '3'
services:
  nginx:
    image: nginx:1.25.3
    container_name: vini123-nginx
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./vini123/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./vini123/nginx/conf.d:/etc/nginx/conf.d
      - ./vini123/nginx/etc/cert:/etc/nginx/cert
      - ./vini123/nginx/logs:/var/log/nginx
      - ./vini123/www:/var/www
      - ./vini123/www/nginx:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    container_name: vini123-php-fpm
    restart: always
    privileged: true
    volumes:
      - ./vini123/www/nginx:/var/www/html
      - ./vini123/www/logs:/var/log/php
    command: bash -c "pecl install redis && docker-php-ext-enable redis && php-fpm"

  mysql:
    image: mysql:8.2
    container_name: vini123-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1
    restart: always
    privileged: true
    environment:
      MYSQL_DATABASE: vini123
      MYSQL_USER: vini123
      MYSQL_PASSWORD: vini2023
      MYSQL_ROOT_PASSWORD: viniroot
    volumes:
      - ./vini123/mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
      image: redis:7.2
      container_name: vini123-redis
      restart: always
      privileged: true
      ports:
        - "6379:6379"
      volumes:
        - ./vini123/redis/redis.conf:/etc/redis/redis.conf
        - ./vini123/redis/data:/data
      command: redis-server /etc/redis/redis.conf

  composer:
    image: composer:2.6.5
    container_name: vini123-composer
    volumes:
      - ./vini123/utils/composer:/var/www/html
    command: install